package com.example.back.enums;

public enum Categoria {
    CONSULTAS_GERAIS,
    PREVENCAO,
    ODONTOPEDIATRIA,
    ORTODONTIA,
    PERIODONTIA,
    ENDODONTIA,
    CIRURGIAS_ODONTOLOGICAS,
    IMPLANTODONTIA,
    PROTESE_DENTARIA,
    ESTETICA_DENTAL,
    ODONTOGERIATRIA,
    RADIOLOGIA_ODONTOLOGICA,
    ODONTOLOGIA_DE_URGENCIA,
    DISFUNCAO_TEMPOROMANDIBULAR,
    ODONTOLOGIA_DO_SONO,
    ODONTOLOGIA_HOSPITALAR,
    ODONTOLOGIA_LEGAL,
    LASERTERAPIA;
}
